
import java.awt.Color;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.Insets;
import java.awt.event.ActionEvent;
import java.util.ArrayList;
import javax.swing.BoxLayout;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextField;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author asogukb
 */
public class BankAccountFrame extends javax.swing.JFrame {

    /**
     * Creates new form BankAccountFrame
     */
    public BankAccountFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        addUserCheckBox = new javax.swing.JCheckBox();
        listUserCheckBox = new javax.swing.JCheckBox();
        withDrawalBalance = new javax.swing.JCheckBox();
        addBalance = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Admin Panel");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(3, 68, 87));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        addUserCheckBox.setBackground(new java.awt.Color(187, 207, 7));
        addUserCheckBox.setForeground(new java.awt.Color(255, 255, 255));
        addUserCheckBox.setText("Kullanıcı Ekle");
        addUserCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addUserCheckBoxActionPerformed(evt);
            }
        });

        listUserCheckBox.setBackground(new java.awt.Color(187, 207, 7));
        listUserCheckBox.setForeground(new java.awt.Color(255, 255, 255));
        listUserCheckBox.setText("Kullanıcıları Listele");
        listUserCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listUserCheckBoxActionPerformed(evt);
            }
        });

        withDrawalBalance.setBackground(new java.awt.Color(187, 207, 7));
        withDrawalBalance.setForeground(new java.awt.Color(255, 255, 255));
        withDrawalBalance.setText("Para Çekme");
        withDrawalBalance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                withDrawalBalanceActionPerformed(evt);
            }
        });

        addBalance.setBackground(new java.awt.Color(187, 207, 7));
        addBalance.setForeground(new java.awt.Color(255, 255, 255));
        addBalance.setText("Para Yatırma");
        addBalance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBalanceActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Yapmak İstediğiniz İşlemi Seçiniz");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addUserCheckBox)
                    .addComponent(listUserCheckBox)
                    .addComponent(withDrawalBalance)
                    .addComponent(addBalance))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(113, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(100, 100, 100))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(53, 53, 53)
                .addComponent(addUserCheckBox)
                .addGap(33, 33, 33)
                .addComponent(listUserCheckBox)
                .addGap(29, 29, 29)
                .addComponent(withDrawalBalance)
                .addGap(29, 29, 29)
                .addComponent(addBalance)
                .addContainerGap(77, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void addUserCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addUserCheckBoxActionPerformed

        if (addUserCheckBox.isSelected()) {
            JFrame frame = new JFrame();
            frame.setTitle("Kullanıcı Ekle");

            JPanel mainPanel = new JPanel();
            mainPanel.setLayout(new BoxLayout(mainPanel, BoxLayout.Y_AXIS));

            JPanel headingPanel = new JPanel();
            JLabel headingLabel = new JLabel("Paralel Banka Uygulamasına Kullanıcı Ekleyin");
            headingPanel.add(headingLabel);

            JPanel panel = new JPanel(new GridBagLayout());
            GridBagConstraints constr = new GridBagConstraints();
            constr.insets = new Insets(5, 5, 5, 5);
            constr.anchor = GridBagConstraints.WEST;
            constr.gridx = 0;
            constr.gridy = 0;

            JLabel nameLabel = new JLabel("Ad :");
            JLabel userNameLabel = new JLabel("Kullanıcı Adı :");
            JLabel balanceLabel = new JLabel("Hesaptaki Para Değeri :");

            JTextField addNameTxt = new JTextField(20);
            JTextField addUserNameTxt = new JTextField(20);
            JTextField balanceTxt = new JTextField(20);

            panel.add(nameLabel, constr);
            constr.gridx = 1;
            panel.add(addNameTxt, constr);
            constr.gridx = 0;
            constr.gridy = 1;

            panel.add(userNameLabel, constr);
            constr.gridx = 1;
            panel.add(addUserNameTxt, constr);
            constr.gridx = 0;
            constr.gridy = 2;

            panel.add(balanceLabel, constr);
            constr.gridx = 1;
            panel.add(balanceTxt, constr);
            constr.gridy = 3;

            constr.gridwidth = 2;
            constr.anchor = GridBagConstraints.CENTER;

            JButton button = new JButton("Kullanıcı Ekle");
            button.addActionListener((ActionEvent e) -> {
                headingLabel.setText("Kayıt işlemi başarılı. Yeni kullanıcı oluşturabilirsiniz.");

                if (!"".equals(addNameTxt.getText()) && !"".equals(balanceTxt.getText()) && !"".equals(addUserNameTxt.getText())) {
                    Person person = new Person(addNameTxt.getText(), addUserNameTxt.getText(), Integer.parseInt(balanceTxt.getText()));
                    newPerson.add(person);
                    addNameTxt.setText("");
                    balanceTxt.setText("");
                    addUserNameTxt.setText("");
                } else {
                    BankAccountFrame error = new BankAccountFrame();
                    JOptionPane.showMessageDialog(error,
                        "Lütfen sizden istenilen bilgileri doldurun.",
                        "Kullanıcı Ekleme Hatası",
                        JOptionPane.ERROR_MESSAGE);
                }
            });

            panel.add(button, constr);
            mainPanel.add(headingPanel);
            mainPanel.add(panel);

            frame.add(mainPanel);
            frame.pack();
            frame.setSize(400, 400);
            frame.setLocationRelativeTo(null);
            frame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
            frame.getContentPane().setBackground( new Color(3, 68, 87) );
            frame.setVisible(true);
            addUserCheckBox.setSelected(false);
        }
    }//GEN-LAST:event_addUserCheckBoxActionPerformed

    private void listUserCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listUserCheckBoxActionPerformed
        if (listUserCheckBox.isSelected()) {

            JFrame frame = new JFrame();
            frame.setTitle("Kullanıcılar");
            JPanel mainPanel = new JPanel();
            mainPanel.setLayout(new BoxLayout(mainPanel, BoxLayout.Y_AXIS));

            JPanel panel = new JPanel(new GridBagLayout());
            GridBagConstraints constr = new GridBagConstraints();
            constr.insets = new Insets(5, 5, 5, 5);
            constr.anchor = GridBagConstraints.WEST;
            constr.gridx = 0;
            constr.gridy = 0;
            String data[][] = new String[newPerson.size()][3];
            for (int i = 0; i < newPerson.size(); i++) {
                for (int j = 0; j <= 0; j++) {
                    data[i][j] = newPerson.get(i).name;
                    data[i][j + 1] = newPerson.get(i).userName;
                    data[i][j + 2] = String.valueOf(newPerson.get(i).balance);
                }
            }
            String column[] = {"Ad", "Kullanıcı Adı", "Para Miktarı"};
            JTable jt = new JTable(data, column);
            jt.setBounds(30, 40, 200, 300);
            JScrollPane sp = new JScrollPane(jt);
            frame.add(sp);
            frame.setSize(300, 400);
            frame.setVisible(true);
            mainPanel.add(panel);

            frame.add(mainPanel);
            frame.pack();
            frame.setSize(400, 400);
            frame.setLocationRelativeTo(null);
            frame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

            frame.setVisible(true);
            listUserCheckBox.setSelected(false);
        }
    }//GEN-LAST:event_listUserCheckBoxActionPerformed

    private void withDrawalBalanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_withDrawalBalanceActionPerformed
        if (withDrawalBalance.isSelected()) {
            JFrame frame = new JFrame();
            frame.setTitle("Para Çekme");

            JPanel mainPanel = new JPanel();
            mainPanel.setLayout(new BoxLayout(mainPanel, BoxLayout.Y_AXIS));

            JPanel headingPanel = new JPanel();
            JLabel headingLabel = new JLabel("Kullanıcıların Hesaplarından Çekmek İstedikleri Para Tutarını Giriniz.");
            headingPanel.add(headingLabel);

            JPanel panel = new JPanel(new GridBagLayout());

            GridBagConstraints constr = new GridBagConstraints();
            constr.insets = new Insets(5, 5, 5, 5);
            constr.anchor = GridBagConstraints.WEST;
            constr.gridx = 0;
            constr.gridy = 0;

            JLabel balanceLabel = new JLabel("Para Miktarı :");
            JTextField addBalanceTxt = new JTextField(20);
            panel.add(balanceLabel, constr);
            constr.gridx = 1;
            panel.add(addBalanceTxt, constr);
            constr.gridx = 0;
            constr.gridy = 1;
            constr.gridwidth = 2;
            constr.anchor = GridBagConstraints.CENTER;

            JButton button = new JButton("Para Çek");
            button.addActionListener((ActionEvent e) -> {
                headingLabel.setText("Para Çekme İşlemi başarıyla tamamlanmıştır");

                Account account = new Account(newPerson.get(0).balance);
                AccountHolder accountHolder = new AccountHolder(account, Integer.valueOf(addBalanceTxt.getText()));

                Thread t1 = new Thread(accountHolder);
                Thread t2 = new Thread(accountHolder);
                t1.setName(newPerson.get(0).name);
                t2.setName(newPerson.get(1).name);

                t1.start();
                t2.start();

            });
            panel.add(button, constr);
            mainPanel.add(headingPanel);
            mainPanel.add(panel);

            frame.add(mainPanel);
            frame.pack();
            frame.setSize(400, 400);
            frame.setLocationRelativeTo(null);
            frame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

            frame.setVisible(true);
            addUserCheckBox.setSelected(false);
        }
    }//GEN-LAST:event_withDrawalBalanceActionPerformed

    private void addBalanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBalanceActionPerformed
        if (addBalance.isSelected()) {
            JFrame frame = new JFrame();
            frame.setTitle("Para Yatırma");

            JPanel mainPanel = new JPanel();
            mainPanel.setLayout(new BoxLayout(mainPanel, BoxLayout.Y_AXIS));

            JPanel headingPanel = new JPanel();
            JLabel headingLabel = new JLabel("Yatırılacak para tutarını giriniz.");
            headingPanel.add(headingLabel);

            JPanel panel = new JPanel(new GridBagLayout());

            GridBagConstraints constr = new GridBagConstraints();
            constr.insets = new Insets(5, 5, 5, 5);
            constr.anchor = GridBagConstraints.WEST;
            constr.gridx = 0;
            constr.gridy = 0;

            JLabel balanceLabel = new JLabel("Para Miktarı :");
            JTextField addBalanceTxt = new JTextField(20);
            panel.add(balanceLabel, constr);
            constr.gridx = 1;
            panel.add(addBalanceTxt, constr);
            constr.gridx = 0;
            constr.gridy = 1;
            constr.gridwidth = 2;
            constr.anchor = GridBagConstraints.CENTER;

            JButton button = new JButton("Para Aktar");
            button.addActionListener((ActionEvent e) -> {
                headingLabel.setText("Para Çekme İşlemi başarıyla tamamlanmıştır");

                Account accountFirst = new Account(newPerson.get(0).balance);
                Account accountSecond = new Account(newPerson.get(1).balance);

                AccountThread thread1 = new AccountThread(accountFirst, accountSecond, Integer.valueOf(addBalanceTxt.getText()));
                AccountThread thread2 = new AccountThread(accountSecond, accountFirst, Integer.valueOf(addBalanceTxt.getText()));

                Thread t1 = new Thread(thread1);
                Thread t2 = new Thread(thread2);
                t1.setName(newPerson.get(0).name);
                t2.setName(newPerson.get(1).name);

                t1.start();
                t2.start();

            });
            panel.add(button, constr);
            mainPanel.add(headingPanel);
            mainPanel.add(panel);

            frame.add(mainPanel);
            frame.pack();
            frame.setSize(400, 400);
            frame.setLocationRelativeTo(null);
            frame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

            frame.setVisible(true);
            addUserCheckBox.setSelected(false);
        }
    }//GEN-LAST:event_addBalanceActionPerformed

    /**
     */
    public static ArrayList<Person> newPerson = new ArrayList<>();
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BankAccountFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new BankAccountFrame().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox addBalance;
    private javax.swing.JCheckBox addUserCheckBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JCheckBox listUserCheckBox;
    private javax.swing.JCheckBox withDrawalBalance;
    // End of variables declaration//GEN-END:variables
}
